### ISSUE TITLE
Dark Mode for Parseq

### ISSUE THREAD

**Issue by DonKDev** [rewbs/sd-parseq#111]
it would be very nice if there was a darkmode for the parseq html page because i often work at night

**Comment by rewbs** [comment]
I don't think it would be too hard to add, it's mostly done by MUI (https://mui.com/material-ui/customization/dark-mode/) but I have a few hard-coded colours in Parseq that would need to be changed to alternate depending on the them.

Good first ticket for anyone wanting to contribute! :)

**Comment by conorluddy** [comment]
Will take a look. Gotta love MUI 😆 

<img width="1792" alt="Screenshot 2023-06-08 at 09 18 28" src="https://github.com/rewbs/sd-parseq/assets/846373/4e2cce52-2f4e-4328-b22d-22abe9a93b6b">

**Comment by conorluddy** [comment]
WIP 👍🏼 

![Kapture 2023-06-08 at 18 11 07](https://github.com/rewbs/sd-parseq/assets/846373/9d5b4521-e136-4700-83a8-ace5f747200d)

Branch is here https://github.com/conorluddy/sd-parseq/tree/feature/111/dark-mode

**Comment by brbbbq** [comment]
I openly support Dark Mode :)

The example above is looking pretty good.

**Comment by conorluddy** [comment]
I need to figure out a few things before opening a PR for it. Ideally it would remember your choice so that the next time you show the page it's still in dark/light mode. For that we need to persist it. Ideally this would follow the existing pattern for how Robin is persisting the other document settings, but then that raises a question of whether that's the best place to store something like a dark mode preference, as it's probably agnostic to the actual document. (you probably don't want different versions having different dark mode settings, it's more likely something you want to store for everything.). Then there's a question of where the switch/button lives. If it's in the Header component like it is in the gif above, then it doesn't have the context of those other document settings, because the main UI component is a sibling of the Header 🤔 
I don't want to muddy up the root component either. I'll have another look at it today and see what comes to mind. There's a few bits of styling that would need to be adjusted still too, like the white graphs and various borders and text colours and the footer. Nothing too challenging though.

**Comment by rewbs** [comment]
Awesome work so far! Thanks @conorluddy , those are all good thoughts. I agree it doesn't make sense to save Dark Mode preference at the document level. I'm very open to us introducing a separate indexeddb table for more global settings like colour schemes. I'm sure it would come in useful for a range of things.

In terms of where the toggle lives, I think from a UX perspective it's fine where you've put it. That could eventually become a button for a "global settings" dialog that would include the dark mode toggle, when we get more of such global settings. 

Another option is in the footer. I recently added a pin button/toggle on the left, and there's some blank space below it.

In terms of how to to technically get the right state passed around, I assume we'd need to [lift](https://react.dev/learn/sharing-state-between-components) the dark mode state at least to the Deforum component level, if not the index.js component if we want dark mode to work in the document browser too. I'm also open to the header component to be moved up to index.js as long as /raw continues to render without a header. I'm not open to the main GUI components becoming a children of the Header component.

Thanks a lot for your help!!

**Comment by conorluddy** [comment]
Nice one Robin - thanks for the info! More than happy to try to help, I've had a lot of fun generating videos with Parseq. Leave it with me and I'll get it updated asap with those guidelines 👍🏼

**Comment by rewbs** [comment]
Done in https://github.com/rewbs/sd-parseq/pull/179, heading to staging.

**Comment by rewbs** [comment]
This is now live! :)
